<a href="https://colab.research.google.com/github/shafiqul-cyber/Skill_Morph_Practice_from_Instrictor-/blob/Skill_Morph/Assignment_3_NumPy_and_Pandas_for_Data_Science.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
"""
Student Performance Dataset Analysis
Dataset Information
Student Performance Dataset (StudentsPerformance.csv)

1000 students with academic performance data
8 columns: gender, race/ethnicity, parental level of education, lunch, test preparation course, math score, reading score, writing score
Score Range: 0-100 for each subject
Demographics: Male/Female, 5 ethnic groups, 6 education levels, standard/free lunch, test prep completed/none
"""

'\nStudent Performance Dataset Analysis\nDataset Information\nStudent Performance Dataset (StudentsPerformance.csv)\n\n1000 students with academic performance data\n8 columns: gender, race/ethnicity, parental level of education, lunch, test preparation course, math score, reading score, writing score\nScore Range: 0-100 for each subject\nDemographics: Male/Female, 5 ethnic groups, 6 education levels, standard/free lunch, test prep completed/none\n'

In [ ]:
#Task 1.1: Data Loading and Exploration
import numpy as np
import pandas as pd
# Load the dataset
#df = pd.read_csv('StudentsPerformance.csv')

# Your tasks:
# 1. Display first 10 rows
# 2. Show dataset shape and info()
# 3. Display unique values in each categorical column
# 4. Show basic statistics for all score columns

# Your code here:
from google.colab import files
uploaded = files.upload()

# Load the uploaded file
import io
df = pd.read_csv(io.BytesIO(uploaded['StudentsPerformance.csv']))

Saving StudentsPerformance.csv to StudentsPerformance.csv

In [ ]:
# 1. Display first 10 rows
df.head(10)

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score
0,female,group B,bachelor's degree,standard,none,72,72,74
1,female,group C,some college,standard,completed,69,90,88
2,female,group B,master's degree,standard,none,90,95,93
3,male,group A,associate's degree,free/reduced,none,47,57,44
4,male,group C,some college,standard,none,76,78,75
5,female,group B,associate's degree,standard,none,71,83,78
6,female,group B,some college,standard,completed,88,95,92
7,male,group B,some college,free/reduced,none,40,43,39
8,male,group D,high school,free/reduced,completed,64,64,67
9,female,group B,high school,free/reduced,none,38,60,50

In [ ]:
# 2. Show dataset shape and info()

print("Dataser Shape: ", df.shape) #dataset shape
print("Dataset info: " , df.info()) # dataset info

Dataser Shape:  (1000, 8)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB
Dataset info:  None

In [ ]:
# 3. Display unique values in each categorical column
print(df['gender'].unique())
print(df['race/ethnicity'].unique())

['female' 'male']
['group B' 'group C' 'group A' 'group D' 'group E']

In [ ]:

print(df['parental level of education'].unique())
print(df['lunch'].unique())
print(df['test preparation course'].unique())
print(df['math score'].unique())
print(df['reading score'].unique())
print(df['writing score'].unique())

['female' 'male']
['group B' 'group C' 'group A' 'group D' 'group E']
[ 356  425   54  899  264  378   72  955  563  966  722  535  222  858
  998  910  788  505  929  308  334  480  400  617  586  757   16  165
  285  743  770  809  693  145  241  981  830 1000  204  962  920  669
  648  947  874  985  185  941  991  936  454  110   12   87  845    9
  123   46  132   61  996    4   21   28  888  976  979   99   38  969
  990  994  993   23  972  988  983   33  997  995  999]
['standard' 'free/reduced']
['none' 'completed']
[ 72  69  90  47  76  71  88  40  64  38  58  65  78  50  18  46  54  66
  44  74  73  67  70  62  63  56  97  81  75  57  55  53  59  82  77  33
  52   0  79  39  45  60  61  41  49  30  80  42  27  43  68  85  98  87
  51  99  84  91  83  89  22 100  96  94  48  35  34  86  92  37  28  24
  26  95  36  29  32  93  19  23   8]
[ 72  90  95  57  78  83  43  64  60  54  52  81  53  75  89  32  42  58
  69  73  71  74  70  65  87  56  61  84  55  44  41  85  59  17  39  80
  37  63  51  49  26  68  45  47  86  34  79  66  67  91 100  76  77  82
  92  93  62  88  50  28  48  46  23  38  94  97  99  31  96  24  29  40]
[ 74  88  93  44  75  78  92  39  67  50  52  43  73  70  58  86  28  46
  61  63  53  80  72  55  65  38  82  79  83  59  57  54  68  66  62  76
  48  42  87  49  10  34  71  37  56  41  22  81  45  36  89  47  90 100
  64  98  51  40  84  69  33  60  85  91  77  27  94  95  19  35  32  96
  97  99  15  30  23]

In [ ]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,BMI,Rank,pl_education
0,female,group B,356,standard,none,72,72,74,NaN,356,356
1,female,group C,425,standard,completed,69,90,88,NaN,425,425
2,female,group B,54,standard,none,90,95,93,NaN,54,54
3,male,group A,899,free/reduced,none,47,57,44,NaN,899,899
4,male,group C,264,standard,none,76,78,75,NaN,264,264

In [ ]:
# 4. Show basic statistics for all score columns

print("Basic Statistics: ",df.describe())

Basic Statistics:         math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [ ]:
#Task 1.2: NumPy Array Operations
# Convert score columns to numpy arrays
math_scores = df['math score'].values
reading_scores = df['reading score'].values
writing_scores = df['writing score'].values

# Your tasks:
# 1. Calculate mean, median, std, min, max for each subject using NumPy
# 2. Find total students who scored above 80 in math
# 3. Find total students who scored below 50 in any subject
# 4. Calculate the overall average score across all three subjects

# Expected output example:
# Math - Mean: 66.1, Median: 66.0, Std: 15.2
# Students with math > 80: 132
# Students with any score < 50: 178

# Your code here:

In [ ]:
# 1. Calculation of  mean, median, std, min, max for each subject using NumPy
# for math_scores
print("Mean: ", np.mean(math_scores))
print("median: ", np.median(math_scores))
print("Standard Deviation: ", np.std(math_scores))
print("Min: ", np.min(math_scores))
print("Max: ",np.max(math_scores))

Mean:  66.089
median:  66.0
Standard Deviation:  15.155496659628149
Min:  0
Max:  100

In [ ]:
# for reading_score
print("Mean: ", np.mean(reading_scores))
print("Median: ", np.median(reading_scores))
print("Standard Deviation: ", np.std(reading_scores))
print("Min: ", np.min(reading_scores))
print("Max: ",np.max(reading_scores))

Mean:  69.169
Median:  70.0
Standard Deviation:  14.592890015346516
Min:  17
Max:  100

In [ ]:
# for writing_score
print("Mean: ", np.mean(writing_scores))
print("Median: ", np.median(writing_scores))
print("Standard Deviation: ", np.std(writing_scores))
print("Minimum: ", np.min(writing_scores))
print("Maximum: ",np.max(writing_scores))

Mean:  68.054
Median:  69.0
Standard Deviation:  15.188057281956768
Minimum:  10
Maximum:  100

In [ ]:
math_scores = df['math score'].values

In [ ]:
# 2. Find total students who scored above 80 in math
math_above_80=  df['math score']>80
print("Total Student Above 80: ",  np.sum(math_above_80))

Total Student Above 80:  176

In [ ]:
# 3. Find total students who scored below 50 in any subject
scored_below_50=( df['math score']<50) |  ( df['reading score']<50) |  ( df['writing score']<50)
print(np.sum(scored_below_50))

188

In [ ]:
# 4. calculation the overall average score across all three subjects
math_average=np.mean(math_scores)
reading_average=np.mean(reading_scores)
writing_avarage=np.mean(writing_scores)

overall_avarage=(math_average+reading_average+writing_avarage)/3
print(overall_avarage)

67.77066666666666

In [ ]:
# Task 2.1: Identify and Handle Missing Data
# Check the dataset for any missing values
# Your tasks:
# 1. Check for null values in each column using .isnull().sum()
# 2. Check for any impossible values (scores > 100 or < 0)
# 3. Display summary of data quality

# Note: This dataset is clean, but let's verify!

# Your code here:

In [ ]:
# 1. Check for null values in each column using .isnull().sum()
print("Missing values in each column:")
print(df.isnull().sum())

Missing values in each column:
gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

In [ ]:
# 2. Check for any impossible values (scores > 100 or < 0)
print("Math Score column:")
print("less than Zero values in each column:", (df['math score']<0).sum())
print("Greater than 100 values in each column:", (df['math score']>100).sum())

print("reading Score column:")
print("less than Zero values in each column:", (df['reading score']<0).sum())
print("Greater than 100 values in each column:", (df['reading score']>100).sum())


print("writing Score column:")
print("less than Zero values in each column:", (df['writing score']<0).sum())
print("Greater than 100 values in each column:", (df['writing score']>100).sum())

Math Score column:
less than Zero values in each column: 0
Greater than 100 values in each column: 0
reading Score column:
less than Zero values in each column: 0
Greater than 100 values in each column: 0
writing Score column:
less than Zero values in each column: 0
Greater than 100 values in each column: 0

In [ ]:
# 3. Display summary of data quality
print(df.head())
print(df.tail())
print(df.info())
print(df.describe())

   gender race/ethnicity parental level of education         lunch  \
0  female        group B           bachelor's degree      standard
1  female        group C                some college      standard
2  female        group B             master's degree      standard
3    male        group A          associate's degree  free/reduced
4    male        group C                some college      standard

  test preparation course  math score  reading score  writing score
0                    none          72             72             74
1               completed          69             90             88
2                    none          90             95             93
3                    none          47             57             44
4                    none          76             78             75
     gender race/ethnicity parental level of education         lunch  \
995  female        group E             master's degree      standard
996    male        group C                 high school  free/reduced
997  female        group C                 high school  free/reduced
998  female        group D                some college      standard
999  female        group D                some college  free/reduced

    test preparation course  math score  reading score  writing score
995               completed          88             99             95
996                    none          62             55             55
997               completed          59             71             65
998               completed          68             78             77
999                    none          77             86             86
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 8 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
dtypes: int64(3), object(5)
memory usage: 62.6+ KB
None
       math score  reading score  writing score
count  1000.00000    1000.000000    1000.000000
mean     66.08900      69.169000      68.054000
std      15.16308      14.600192      15.195657
min       0.00000      17.000000      10.000000
25%      57.00000      59.000000      57.750000
50%      66.00000      70.000000      69.000000
75%      77.00000      79.000000      79.000000
max     100.00000     100.000000     100.000000

In [ ]:
#Task 2.2: Create and Fix Missing Value
# Artificially create missing data for practice
import numpy as np

# Your tasks:
# 1. Make a copy of the dataset: df_practice = df.copy()
# 2. Randomly set 50 math scores to np.nan
# 3. Randomly set 30 writing scores to np.nan
# 4. Fill missing math scores with the MEDIAN math score
# 5. Fill missing writing scores with the MEAN writing score
# 6. Verify no missing values remain

# Steps to follow:
# Step 1: Create copy and show original missing values
df_practice = df.copy()
print("Original missing values:", df_practice.isnull().sum())

# Step 2: Create missing data
np.random.seed(42)  # For reproducible results
missing_math_idx = np.random.choice(df_practice.index, 50, replace=False)
missing_writing_idx = np.random.choice(df_practice.index, 30, replace=False)

# Continue the task...
# Your code here:

In [ ]:
# 1.a copy of the dataset:
df_practice = df.copy()
print("Original missing values:", df_practice.isnull().sum())

Original missing values: gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

In [ ]:
# 2. Randomly set 50 math scores to np.nan
#Create missing data
np.random.seed(42)  # For reproducible results
missing_math_idx = np.random.choice(df_practice.index, 50, replace=None)
missing_writing_idx = np.random.choice(df_practice.index, 30, replace=False)

In [ ]:
print(missing_math_idx)

[521 737 740 660 411 678 626 513 859 136 811  76 636 973 938 899 280 883
 761 319 549 174 371 527 210 235 101 986 902 947 346 139 621 499 370 198
 687 584 901  59 328  96 312 974 299 277 924 601 439 837]

In [ ]:
# Assign NaN to those 50 rows in math score
df_practice.loc[missing_math_idx, 'math score'] = np.nan

In [ ]:
print("Created missing values:", df_practice.isnull().sum())

Created missing values: gender                          0
race/ethnicity                  0
parental level of education     0
lunch                           0
test preparation course         0
math score                     50
reading score                   0
writing score                   0
dtype: int64

In [ ]:
print("Created missing values:", df_practice.isnull().sum())

Created missing values: gender                          0
race/ethnicity                  0
parental level of education     0
lunch                           0
test preparation course         0
math score                     50
reading score                   0
writing score                  30
dtype: int64

In [ ]:
# 3. Randomly set 30 writing scores to np.nan
df_practice.loc[missing_writing_idx,'writing score']=np.nan

In [ ]:
# 4. Fill missing math scores with the MEDIAN math score
df_practice['math score']=df['math score'].fillna(df['math score'].median())

In [ ]:
print("Created missing values:", df_practice.isnull().sum())

Created missing values: gender                          0
race/ethnicity                  0
parental level of education     0
lunch                           0
test preparation course         0
math score                      0
reading score                   0
writing score                  30
dtype: int64

In [ ]:
# 5. Fill missing writing scores with the MEAN writing score
df_practice['writing score']=df_practice['writing score'].fillna(df_practice['writing score'].mean())

In [ ]:
# 6. Verification of  no missing values remain
print("Created missing values:", df_practice.isnull().sum())

Created missing values: gender                         0
race/ethnicity                 0
parental level of education    0
lunch                          0
test preparation course        0
math score                     0
reading score                  0
writing score                  0
dtype: int64

In [ ]:
#Task 3.1:Answer Simple Questions About Student Performance
# Your tasks:
# 1. Display first 5 rows using .head()
# 2. Display last 5 rows using .tail()
# 3. Show dataset shape using .shape
# 4. Show column names using .columns
# 5. Show data types using .dtypes
# 6. Show basic info using .info()

# Your code here:

In [ ]:
# 1. Display first 5 rows using .head()

print("First 5 rows in dataset: ", df.head())

First 5 rows in dataset:     gender race/ethnicity parental level of education         lunch  \
0  female        group B           bachelor's degree      standard
1  female        group C                some college      standard
2  female        group B             master's degree      standard
3    male        group A          associate's degree  free/reduced
4    male        group C                some college      standard

  test preparation course  math score  reading score  writing score  BMI
0                    none          72             72             74  NaN
1               completed          69             90             88  NaN
2                    none          90             95             93  NaN
3                    none          47             57             44  NaN
4                    none          76             78             75  NaN

In [ ]:
# 2. Display last 5 rows using .tail()
print("display last 5 rows: ", df.tail())

display last 5 rows:       gender race/ethnicity parental level of education         lunch  \
995  female        group E             master's degree      standard
996    male        group C                 high school  free/reduced
997  female        group C                 high school  free/reduced
998  female        group D                some college      standard
999  female        group D                some college  free/reduced

    test preparation course  math score  reading score  writing score  BMI
995               completed          88             99             95  NaN
996                    none          62             55             55  NaN
997               completed          59             71             65  NaN
998               completed          68             78             77  NaN
999                    none          77             86             86  NaN

In [ ]:
# 3. Show dataset shape using .shape

print("Shape of Dataset: ", df.shape)

Shape of Dataset:  (1000, 9)

In [ ]:
# 4. Show column names using .columns
print("Column names:", df.columns.tolist())

Column names: ['gender', 'race/ethnicity', 'parental level of education', 'lunch', 'test preparation course', 'math score', 'reading score', 'writing score', 'BMI']

In [ ]:
# 5. Show data types using .dtypes

print("Data types: ", df.dtypes)
# 6. Show basic info using .info()
print("Basic Info: ", df.info())

Data types:  gender                          object
race/ethnicity                  object
parental level of education     object
lunch                           object
test preparation course         object
math score                       int64
reading score                    int64
writing score                    int64
BMI                            float64
dtype: object
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 9 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   gender                       1000 non-null   object
 1   race/ethnicity               1000 non-null   object
 2   parental level of education  1000 non-null   object
 3   lunch                        1000 non-null   object
 4   test preparation course      1000 non-null   object
 5   math score                   1000 non-null   int64
 6   reading score                1000 non-null   int64
 7   writing score                1000 non-null   int64
 8   BMI                          0 non-null      float64
dtypes: float64(1), int64(3), object(5)
memory usage: 70.4+ KB
Basic Info:  None

In [ ]:
#Task 3.2: Basic Groupby Analysis
# Comprehensive groupby analysis
# Your tasks:

# 1. Group by 'gender' and calculate:
#    - Average scores in all subjects
#    - Count of students

# 2. Group by 'test preparation course' and show:
#    - Mean scores for each subject
#    - Show which subject benefits most from test prep

# 3. Group by 'parental level of education' and calculate:
#    - Average math score for each education level
#    - Rank education levels by math performance

# 4. Group by 'lunch' type and show:
#    - Average scores for each subject
#    - Count of students in each lunch category

# Your code here:

In [ ]:
# 1. Group by 'gender' and calculate:
#    - Average scores in all subjects
#    - Count of students
gender_group=df.groupby('gender')[['math score', 'reading score', 'writing score']].agg(['mean','count'])
print(gender_group)

       math score       reading score       writing score
             mean count          mean count          mean count
gender
female  63.633205   518     72.608108   518     72.467181   518
male    68.728216   482     65.473029   482     63.311203   482

In [ ]:
# 2. Group by 'test preparation course' and show:
#    - Mean scores for each subject
#    - Show which subject benefits most from test prep

test_group=df.groupby('test preparation course')[['math score','reading score','writing score']].mean()
print(test_group)
print("Subject benefit: ", test_group['writing score'])

                         math score  reading score  writing score
test preparation course
completed                 69.695531      73.893855      74.418994
none                      64.077882      66.534268      64.504673
Subject benefit:  test preparation course
completed    74.418994
none         64.504673
Name: writing score, dtype: float64

In [ ]:
# 3. Group by 'parental level of education' and calculate:
#    - Average math score for each education level
#    - Rank education levels by math performance

pl_education=df.groupby('parental level of education')['math score'].mean()
print(pl_education)

parental level of education
associate's degree    67.882883
bachelor's degree     69.389831
high school           62.137755
master's degree       69.745763
some college          67.128319
some high school      63.497207
Name: math score, dtype: float64

In [ ]:
pdata=pd.DataFrame(pl_education) # for rank we need to convert it to pandas dataframe

In [ ]:
print("Rank education levels by math performance")
pdata["Rank"] = pdata["math score"].rank(ascending=False).astype(int)
print(pdata.sort_values("Rank"))

Rank education levels by math performance
                             math score  Rank
parental level of education
master's degree               69.745763     1
bachelor's degree             69.389831     2
associate's degree            67.882883     3
some college                  67.128319     4
some high school              63.497207     5
high school                   62.137755     6

In [ ]:
# 4. Group by 'lunch' type and show:
#    - Average scores for each subject
#    - Count of students in each lunch category

lung_group=df.groupby('lunch')[['math score','reading score','writing score']].agg(['mean','count'])
print(lung_group)

             math score       reading score       writing score
                   mean count          mean count          mean count
lunch
free/reduced  58.921127   355     64.653521   355     63.022535   355
standard      70.034109   645     71.654264   645     70.823256   645

In [ ]:
#Task 3.3: Use your data analysis skills to answer these easy questions:

# 1. Who performs better in math - males or females?
#    - Calculate average math score by gender
#    - Show the difference between male and female average

# 2. Which subject do students perform best in overall?
#    - Calculate the overall average for math, reading, and writing
#    - Rank the subjects from highest to lowest average score

# 3. What's the impact of parental education?
#    - Find the average total score for each parental education level
#    - Identify which education level leads to highest student performance

In [ ]:
# 1. Who performs better in math - males or females?
#    - Calculate average math score by gender
#    - Show the difference between male and female average

math=df.groupby('gender')['math score'].mean()
print("Average math score by gender: ",math)
print("The difference between male and female average",(math['male']-math['female']))
print("According the result male performs better than female :) ")

Average math score by gender:  gender
female    63.633205
male      68.728216
Name: math score, dtype: float64
The difference between male and female average 5.095011134430216
According the result male performs better than female :)

In [ ]:
df.head()

,gender,race/ethnicity,parental level of education,lunch,test preparation course,math score,reading score,writing score,BMI,Rank,pl_education
0,female,group B,356,standard,none,72,72,74,NaN,356,356
1,female,group C,425,standard,completed,69,90,88,NaN,425,425
2,female,group B,54,standard,none,90,95,93,NaN,54,54
3,male,group A,899,free/reduced,none,47,57,44,NaN,899,899
4,male,group C,264,standard,none,76,78,75,NaN,264,264

In [ ]:
# 2. Which subject do students perform best in overall?
#    - Calculate the overall average for math, reading, and writing
#    - Rank the subjects from highest to lowest average score

m_average=df['math score'].mean()
print("Math Average: ", m_average)
r_average=df['reading score'].mean()
print("Reading Average: ", r_average)
w_average=df['writing score'].mean()
print("Writing Average: ", w_average)

Math Average:  66.089
Reading Average:  69.169
Writing Average:  68.054

In [ ]:
# 3. What's the impact of parental education?
#    - Find the average total score for each parental education level
#    - Identify which education level leads to highest student performance

pl_education=df.groupby('parental level of education')['math score'].mean()
print(pl_education)

parental level of education
4       100.0
9        99.0
12       98.0
16       97.0
21       96.0
        ...
996      22.0
997      19.0
998      18.0
999       8.0
1000      0.0
Name: math score, Length: 81, dtype: float64

In [ ]:
highest_performance = df['parental level of education'].max()
student_highest = df[df['parental level of education'] == highest_performance]
print("highest student performance:", highest_performance)

print(" education level leads to highest student performance:")
print(student_highest[['parental level of education']])

print()

highest student performance: 1000
 education level leads to highest student performance:
    parental level of education
59                         1000